#!/bin/bash
# Copyright (c) 2019 Hush developers

# set working directory to the location of this script
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

# TESTING VALUES, DO NOT USE EXCEPT FOR DEVELOPMENT
NAME=HUSHT
PUBKEY=0392cd7cbdc188de147fa13b38d97ea2e4d612300100fcea14d200907b05f707e8

# chain params
SUPPLY=6250000
FOUNDERS=500
HALVING=129,340000,840000
END=128,340000,5422111
CLIENTNAME=TransientMangrove

# CryptoConditions/Custom Consensus settings
FAUCET=228
HEIR=234
CHANNEL=235
ORACLE=236
GATEWAY=241
CCENABLE=$FAUCET,$HEIR,$CHANNEL,$ORACLE,$GATEWAY

# TODO: support KOMODOD env var to use custom binary
./komodod -ac_name=$NAME -ac_sapling=1          \
    -ac_reward=0,1250000000,675000000           \
    -ac_halving=$HALVING                        \
    -ac_end=$END                                \
    -ac_eras=3 -ac_blocktime=150                \
    -ac_cc=2 -ac_ccenable=$CCENABLE             \
    -ac_founders=$FOUNDERS -ac_supply=$SUPPLY   \
    -ac_perc=10000000                           \
    -clientname=$CLIENTNAME                     \
    -ac_pubkey=$PUBKEY  "$@"
# -addnode=195.201.20.230 -addnode=195.201.137.5

