#!/bin/bash
# Copyright (c) 2019 Hush developers

# set working directory to the location of this script
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

# TESTING VALUES, DO NOT USE EXCEPT FOR DEVELOPMENT
NAME=HUSHT5
# this corresponds to FR address RHushEyeDm7XwtaTWtyCbjGQumYyV8vMjn
SCRIPT=76a9145eb10cf64f2bab1b457f1f25e658526155928fac88ac

# Chain parameters
BLOCKTIME=10
SUPPLY=6250000
FOUNDERS=1
CLIENTNAME=GoldenSandtrout
PERC=11111111

# CryptoConditions/Custom Consensus params
FAUCET=228
HEIR=234
CHANNEL=235
ORACLE=236
GATEWAY=241
DILITHIUM=
CCENABLE=$FAUCET,$HEIR,$CHANNEL,$ORACLE,$GATEWAY

KMD=${KOMODOD:-./komodod}
$KMD -ac_name=$NAME -ac_sapling=1                \
     -ac_blocktime=$BLOCKTIME                    \
     -ac_perc=$PERC                              \
     -ac_cc=2 -ac_ccenable=$CCENABLE             \
     -ac_founders=$FOUNDERS -ac_supply=$SUPPLY   \
     -clientname=$CLIENTNAME                     \
     -ac_script=$SCRIPT  "$@"
