#!/bin/bash
# Copyright (c) 2019-2020 Hush developers
# Released under the GPLv3

# set working directory to the location of this script
# readlink -f does not always exist
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR
DIR="$( cd "$( dirname "$( readlink "${BASH_SOURCE[0]}" )" )" && pwd )"
cd $DIR

NAME=HUSH3

CLI=${KOMODOCLI:-./komodo-cli}
if [ -f $CLI ]; then
   $CLI -ac_name=$NAME "$@"
else
	# We prefix our binary when installed
	# system wide on Debain system, to prevent clashes
	CLI=hush-komodo-cli
    $CLI -ac_name=$NAME "$@"
fi
